# Generated by Django 3.0.8 on 2023-05-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
